# Generated by Django 6.0.3 on 2026-03-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_tasks_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
