# Generated by Django 6.0.3 on 2026-05-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boiler_type', models.CharField(choices=[('BackEnd', 'Backend'), ('Server Side', 'ServerSide'), ('Data Base', 'Database')], default='Server Side', max_length=30)),
                ('boiler_code', models.CharField(max_length=300)),
            ],
        ),
    ]
