# Generated by Django 6.0.3 on 2026-05-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_boiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_link', models.URLField(blank=True, max_length=300)),
                ('service_content', models.CharField(default='Services', max_length=300)),
                ('service_on_content', models.CharField(max_length=300)),
                ('service_off_content', models.CharField(max_length=300)),
                ('service_status', models.BooleanField(default=False)),
            ],
        ),
    ]
