# Generated by Django 6.0.3 on 2026-06-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('pep8', 'pep8'), ('frontend', 'frontend')], default='pep8', max_length=20)),
                ('error_amount', models.IntegerField(default=0)),
                ('error_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
