# Generated by Django 6.0.3 on 2026-06-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_errormanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErrorManager',
            new_name='ErrorManagement',
        ),
    ]
