# Generated by Django 6.0.3 on 2026-06-07 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_rename_errormanager_errormanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormanagement',
            name='error_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
