# Generated by Django 6.0.3 on 2026-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_errormanagement_error_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
