# Generated by Django 6.0.3 on 2026-06-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='icon',
            field=models.CharField(default='bulb-outline', max_length=50),
        ),
    ]
