# Generated by Django 6.0.3 on 2026-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_navbar_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='title',
            field=models.CharField(default='Management', max_length=100),
        ),
    ]
