# Generated by Django 6.0.6 on 2026-06-27 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_navbar_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CveManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_code', models.CharField(max_length=100)),
                ('to_solve', models.URLField(blank=True, max_length=300)),
                ('cve_amount', models.IntegerField(default=0)),
                ('pkg_amount', models.IntegerField(default=0)),
                ('cve_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
