# Generated by Django 6.0.6 on 2026-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_cvemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=100)),
                ('content_subtitle', models.CharField(max_length=400)),
                ('content_1', models.CharField(max_length=400)),
                ('content_2', models.CharField(max_length=400)),
                ('content_3', models.CharField(max_length=400)),
                ('content_4', models.CharField(max_length=400)),
            ],
        ),
    ]
