# Generated by Django 6.0.6 on 2026-06-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='wizard_1',
            field=models.CharField(default='wizard 1', max_length=50),
        ),
        migrations.AddField(
            model_name='content',
            name='wizard_2',
            field=models.CharField(default='wizard 2', max_length=50),
        ),
        migrations.AddField(
            model_name='content',
            name='wizard_3',
            field=models.CharField(default='wizard 3', max_length=50),
        ),
        migrations.AddField(
            model_name='content',
            name='wizard_4',
            field=models.CharField(default='wizard 4', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_1',
            field=models.CharField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_2',
            field=models.CharField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_3',
            field=models.CharField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_4',
            field=models.CharField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_subtitle',
            field=models.CharField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
