# Generated by Django 6.0.6 on 2026-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_content_wizard_1_content_wizard_2_content_wizard_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_1',
            field=models.TextField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_2',
            field=models.TextField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_3',
            field=models.TextField(default='content', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_4',
            field=models.TextField(default='content', max_length=400),
        ),
    ]
